name: Tomorrow's Expiry Email Trigger

on:
  schedule:
    # Aggressive warm-up at 7:30 AM IST (2:00 UTC)
    - cron: "0 2 * * *"
    # Main trigger at 8:00 AM IST (2:30 UTC)
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  wake-render:
    runs-on: ubuntu-latest
    steps:
      - name: Keep hitting Render for 30 minutes
        run: |
          end=$((SECONDS+1800))   # 30 minutes
          while [ $SECONDS -lt $end ]; do
            echo "Pinging Render at $(date)"
            curl -s -o /dev/null https://food-expiry-tracker-backend-h11q.onrender.com/ || true
            sleep 10
          done

  send-email:
    runs-on: ubuntu-latest
    needs: wake-render
    steps:
      - name: Trigger Tomorrow's Food Expiry Email
        run: |
          curl -X GET https://food-expiry-tracker-backend-h11q.onrender.com/test-email
