name: Tomorrow's Expiry Email Trigger

on:
  schedule:
    - cron: "30 2 * * *"   # 8:00 AM IST
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Tomorrow's Food Expiry Email
        run: |
          curl -X GET https://food-expiry-tracker-backend-h11q.onrender.com/test-email
