name: Daily Email Trigger

on:
  schedule:
   - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Food Expiry Email
        run: |
          curl -X GET https://food-expiry-tracker-backend-h11q.onrender.com/test-email
